export const EMPLOYEE_PROFILE_REQUEST = 'EMPLOYEE_PROFILE_REQUEST' 
export const EMPLOYEE_PROFILE_SUCCESS = 'EMPLOYEE_PROFILE_SUCCESS'
export const EMPLOYEE_PROFILE_FAIL = 'EMPLOYEE_PROFILE_FAIL'
export const UPDATE_EMPLOYEE_PROFILE_REQUEST = 'UPDATE_EMPLOYEE_PROFILE_REQUEST'
export const UPDATE_EMPLOYEE_PROFILE_SUCCESS = 'UPDATE_EMPLOYEE_PROFILE_REQUEST'
export const UPDATE_EMPLOYEE_PROFILE_FAIL = 'UPDATE_EMPLOYEE_PROFILE_FAIL'

